CREATE TABLE locker
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    crossfit_box_id BIGINT,
    nid             INTEGER,
    member_id       BIGINT,
    start_date      date,
    end_date        date,
    CONSTRAINT pk_locker PRIMARY KEY (id)
);

ALTER TABLE locker
    ADD CONSTRAINT FK_LOCKER_ON_CROSSFIT_BOX FOREIGN KEY (crossfit_box_id) REFERENCES crossfit_box (id);

ALTER TABLE locker
    ADD CONSTRAINT FK_LOCKER_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (id);