CREATE TABLE event
(
    id         VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    is_active  BOOLEAN,
    start_time time WITHOUT TIME ZONE,
    end_time   time WITHOUT TIME ZONE,
    CONSTRAINT pk_event PRIMARY KEY (id)
);

CREATE TABLE event_person_list
(
    event_id       VARCHAR(255) NOT NULL,
    person_list_id VARCHAR(255) NOT NULL
);

CREATE TABLE person
(
    id          VARCHAR(255) NOT NULL,
    member_id   BIGINT,
    is_presence BOOLEAN      NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_person PRIMARY KEY (id)
);

CREATE TABLE schedule
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    date       date,
    wod_text   TEXT,
    CONSTRAINT pk_schedule PRIMARY KEY (id)
);

CREATE TABLE schedule_events
(
    schedule_id BIGINT       NOT NULL,
    events_id   VARCHAR(255) NOT NULL
);

ALTER TABLE event_person_list
    ADD CONSTRAINT uc_event_person_list_personlist UNIQUE (person_list_id);

ALTER TABLE schedule_events
    ADD CONSTRAINT uc_schedule_events_events UNIQUE (events_id);

ALTER TABLE person
    ADD CONSTRAINT FK_PERSON_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (id);

ALTER TABLE event_person_list
    ADD CONSTRAINT fk_eveperlis_on_event FOREIGN KEY (event_id) REFERENCES event (id);

ALTER TABLE event_person_list
    ADD CONSTRAINT fk_eveperlis_on_person FOREIGN KEY (person_list_id) REFERENCES person (id);

ALTER TABLE schedule_events
    ADD CONSTRAINT fk_scheve_on_event FOREIGN KEY (events_id) REFERENCES event (id);

ALTER TABLE schedule_events
    ADD CONSTRAINT fk_scheve_on_schedule FOREIGN KEY (schedule_id) REFERENCES schedule (id);