CREATE TABLE receipt
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type        VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    start_date  date,
    end_date    date,
    description TEXT,
    CONSTRAINT pk_receipt PRIMARY KEY (id)
);