CREATE TABLE crossfit_box
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    address      VARCHAR(255),
    city         VARCHAR(255),
    state        VARCHAR(255),
    zip_code     VARCHAR(255),
    country      VARCHAR(255),
    phone_number VARCHAR(255),
    email        VARCHAR(255),
    website      VARCHAR(255),
    description  TEXT,
    max_capacity INTEGER,
    founded_date TIMESTAMP WITHOUT TIME ZONE,
    is_active    BOOLEAN,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    owner_name   VARCHAR(255),
    CONSTRAINT pk_crossfit_box PRIMARY KEY (id)
);

ALTER TABLE crossfit_box
    ADD CONSTRAINT uc_crossfit_box_name UNIQUE (name);