CREATE TABLE crossfit_box_coaches
(
    crossfit_box_id BIGINT NOT NULL,
    coaches_id      BIGINT NOT NULL,
    CONSTRAINT pk_crossfit_box_coaches PRIMARY KEY (crossfit_box_id, coaches_id)
);

CREATE TABLE owner
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id        BIGINT,
    crossfit_box_id BIGINT,
    CONSTRAINT pk_owner PRIMARY KEY (id)
);

ALTER TABLE crossfit_box_coaches
    ADD CONSTRAINT uc_crossfit_box_coaches_coaches UNIQUE (coaches_id);

ALTER TABLE owner
    ADD CONSTRAINT FK_OWNER_ON_CROSSFITBOX FOREIGN KEY (crossfit_box_id) REFERENCES crossfit_box (id);

ALTER TABLE owner
    ADD CONSTRAINT FK_OWNER_ON_OWNER FOREIGN KEY (owner_id) REFERENCES member (id);

ALTER TABLE crossfit_box_coaches
    ADD CONSTRAINT fk_croboxcoa_on_crossfit_box FOREIGN KEY (crossfit_box_id) REFERENCES crossfit_box (id);

ALTER TABLE crossfit_box_coaches
    ADD CONSTRAINT fk_croboxcoa_on_member FOREIGN KEY (coaches_id) REFERENCES member (id);